In [1]:
import numpy as np
import pandas as pd

In [2]:
'''
Now you will read a dataset for Machine Learning using pandas
'''
def readData (filename, col, outputColIndex, delim="\t"):
    '''
    input: filename to read
            columns to read
            outputColIndex
            delimiter
    Task: Read the csv file, and store them dataframes
            Convert the data to numpy
    Output: x_train, y_train
    
    '''
    ### Write your code here. 6 lines of code
    # read the csv file
    # create separate data set for features, and separate for Y. The features column has been given
    # let the feature vector be x_train, and yval be y_train
    #Return x_train, y_train
    features = col[: len(col)-1]
    dfFull = pd.read_csv(filename, names = col, delimiter = delim)
    
    Y = col[outputColIndex]
    dfX = dfFull[features]
    dfY = dfFull [Y]
    x_train, y_train = np.array(dfX), np.array(dfY)
    print (x_train.shape)
    return x_train, y_train
    

In [3]:
cols = ['Frequency', 'AngleOfAttack', 'ChordLength', 'FreeStreamVelocity', 'SuctionSideDisplacementThickness', 
        'ScaledSoundPressureLevel']
filename='airfoil_self_noise.dat.txt'
x_train, y_train = readData(filename, cols, 5)
print (x_train[:5])
print (y_train[:5])


(1503, 5)
[[8.00000e+02 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [1.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [1.25000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [1.60000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]
 [2.00000e+03 0.00000e+00 3.04800e-01 7.13000e+01 2.66337e-03]]
[126.201 125.201 125.951 127.591 127.461]
